/**
 * AUTO-GENERATED by scripts/build-fit-mock-db.mjs — 직접 수정하지 말 것.
 * 원본: data/egg_pages.db (https://fit.rfenms.com, 2026-08-28T03:29:56.724Z)
 * 재생성: node scripts/build-fit-mock-db.mjs
 */

export interface FitMockCategory {
  readonly id: number;
  readonly ord: number;
  readonly name: string;
  readonly disabled: boolean;
}

export interface FitMockPage {
  readonly id: number;
  readonly categoryId: number;
  readonly menuName: string;
  readonly pageFile: string;
  readonly url: string;
  /** 클론 라우트. include/* 파샬은 라우트가 없어 null. */
  readonly route: string | null;
  readonly httpStatus: number;
  readonly finalUrl: string;
  readonly title: string;
  readonly contentLength: number;
  readonly styles: readonly string[];
  readonly scripts: readonly string[];
  /** 원본 화면의 실제 노출 텍스트 전문 (비인증 수집이라 값은 비어 있고 라벨만 있다) */
  readonly textContent: string;
  readonly fetchedAt: string;
}

export interface FitMockFetchSummary {
  readonly site: string;
  readonly categories: number;
  readonly pagesTotal: number;
  readonly pagesOk: number;
  readonly failures: readonly string[];
  readonly fetchedAt: string;
}

export const FIT_MOCK_FETCH_SUMMARY: FitMockFetchSummary = {
  "site": "https://fit.rfenms.com",
  "categories": 3,
  "pagesTotal": 19,
  "pagesOk": 19,
  "failures": [],
  "fetchedAt": "2026-08-28T03:29:56.724Z"
};

export const FIT_MOCK_CATEGORIES: readonly FitMockCategory[] = [
  {
    "id": 1,
    "ord": 1,
    "name": "메뉴",
    "disabled": false
  },
  {
    "id": 2,
    "ord": 2,
    "name": "기타 페이지",
    "disabled": false
  },
  {
    "id": 3,
    "ord": 3,
    "name": "include (내부 파일)",
    "disabled": false
  }
];

export const FIT_MOCK_PAGES: readonly FitMockPage[] = [
  {
    "id": 1,
    "categoryId": 1,
    "menuName": "통합관제",
    "pageFile": "stat.html",
    "url": "https://fit.rfenms.com/stat.html",
    "route": "/fit/stat",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/stat.html",
    "title": "통합관제",
    "contentLength": 17975,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/stat.css?v=0.0.1"
    ],
    "scripts": [
      "//dapi.kakao.com/v2/maps/sdk.js?appkey=183d8d8c6a6aa20033c7ff2308ec58c8&libraries=services",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/echarts.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/stat.js?v=0.0.1"
    ],
    "textContent": "통합관제 정렬 보기 업체명 내림차순 업체명 오름차순 실시간 전력 내림차순 실시간 전력 오름차순 절감률 내림차순 절감률 오름차순 절감금액 내림차순 절감금액 오름차순 제안 정상 통신불량 피크발생 업체명 계약전력 (kW) 실시간 전력 (kW) 절감률 (%/월별) 절감금액 (원/월별) - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 참여 업체 수 제안 - 개 설치 - 개 총 누적 절감 금액 제안 - 원 설치 - 원 - 업데이트 [D+ 0 , 0000.00.00 ~ ] 절감금액 랭킹 TOP 5 오늘 이번주 이번달 올해 알림 오늘 이번주 이번달 올해 사용 전력 (kW) 절감률 (%) 절감금액 (만원) 총 절감금액 계약전력 검침일",
    "fetchedAt": "2026-08-28 12:29:53"
  },
  {
    "id": 2,
    "categoryId": 1,
    "menuName": "업체관리",
    "pageFile": "firm.html",
    "url": "https://fit.rfenms.com/firm.html",
    "route": "/fit/firm",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/firm.html",
    "title": "업체관리",
    "contentLength": 25034,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/common.css?v=0.0.2",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/firm.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "//dapi.kakao.com/v2/maps/sdk.js?appkey=183d8d8c6a6aa20033c7ff2308ec58c8&libraries=services",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/firm.js?v=0.0.4"
    ],
    "textContent": "업체관리 업체관리 1 - 5 / 5 추가 엑셀 프린트 요금표 한전수집 서비스상태 선택 EMS 피크 저압 완료 EMS 준비 피크 준비 저압 준비 EMS 제안 피크 제안 저압 제안 ID 이름 전력타입 한전고객번호 EOI PCT 최근전력 목표전력 운전모드 제어방식 활성 서비스 메모 - - - - - - - - - - - - - ID 이름 업체등록일 전력타입 한전고객번호 연간절감금액 적용전력 최근 5개년 피크 1차/2차 구분 서비스 메모 - - - - - - - - - - - 1 - 5 / 5 prev 1 next 업체관리 이름 기상청지점 선택 서울 부산 대구 강화 백령도 인천 광주 대전 울산 동두천 수원 양평 이천 파주 강릉 대관령 동해 북강릉 북춘천 속초 영월 원주 인제 정선군 철원 춘천 태백 홍천 보은 제천 청주 추풍령 충주 금산 보령 부여 서산 천안 홍성 고창 고창군 군산 남원 부안 순창군 임실 장수 전주 정읍 강진군 고흥 광양시 목포 보성군 순천 여수 영광군 완도 장흥 진도군 해남 흑산도 경주시 구미 문경 봉화 상주 안동 영덕 영주 영천 울릉도 울진 의성 청송군 포항 거제 거창 김해시 남해 밀양 북창원 산청 양산시 의령군 진주 창원 통영 함양군 합천 고산 서귀포 성산 제주 세종 전력타입 전력타입 선택 한전고객번호 EMS 아이디 한전 ID EMS 암호변경 한전 비밀번호 담당자 연락처 주소 검침일 계약전력 요금적용전력 요금적용날짜 목표전력 PCT비 펄스정수 운전모드 수동 자동 제어방식 우선순위 순차제어 EMS 활성 활성 비활성 서비스상태 선택없음 EMS 피크 저압 완료 EMS 준비 피크 준비 저압 준비 EMS 제안 피크 제안 저압 제안 절감계산시작일 투자금액(천원) 이전 전력타입 전력타입 선택 관리계정 메모 확인 취소 주소검색 0,0",
    "fetchedAt": "2026-08-28 12:29:53"
  },
  {
    "id": 3,
    "categoryId": 1,
    "menuName": "한전데이터 수집",
    "pageFile": "research.html",
    "url": "https://fit.rfenms.com/research.html",
    "route": "/fit/research",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/research.html",
    "title": "한전데이터 수집",
    "contentLength": 3529,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/common.css?v=0.0.2",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/research.css?v=0.0.2"
    ],
    "scripts": [
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/research.js?v=0.0.3"
    ],
    "textContent": "한전데이터 수집 한전데이터 수집 전력타입 없음 고객번호 0000000000 한전비번 password 스케줄 상태 스케줄 없음 업데이트정보 없음 수집 요청 월별 요금정보 시간별 전력사용량 kW 일자 검침일 요금적용전력 기본요금 전력량요금 청구요금 경부하전력량 중부하전력량 최대부하전력량 지상역률 진상역률",
    "fetchedAt": "2026-08-28 12:29:53"
  },
  {
    "id": 4,
    "categoryId": 1,
    "menuName": "피크상태",
    "pageFile": "peak.html",
    "url": "https://fit.rfenms.com/peak.html",
    "route": "/fit/peak",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/peak.html",
    "title": "피크상태",
    "contentLength": 27863,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/peak.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/echarts.min.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peak.js?v=0.0.2"
    ],
    "textContent": "피크상태 피크상태 검침일 -일 검침일 기준 적용 데이터정확도 -% 알림 현재 부하 0 개 부하 제어 완료 부하 제어 대기 부하 제어 중 실시간 피크 상태 0 % 00:00 / 15:00 계기시간 00:00:00 시간차 0 초 예측 전력 0 목표 전력 0 현재 전력 0 기준 전력 0 실시간 전력 사용 추이 피크 현황 계약전력 - kW 100% 초과 - 회 90 ~ 100% - 회 80 ~ 90% - 회 전력 사용량 최대부하 중부하 경부하 전력 요금 산업용(을)고압 산업용(갑)저압 목표 절감액 달성 현황 0% 1시간 0 원 목표 절감액 : 0 원 사용전력 0 kw 저압 전력 요금 0 원 고압 전력 요금 0 원 저압 요금 절감률 0 % 0% 오늘 0 원 목표 절감액 : 0 원 사용전력 0 kw 저압 전력 요금 0 원 고압 전력 요금 0 원 저압 요금 절감률 0 % 0% 이번 주 0 원 목표 절감액 : 0 원 사용전력 0 kw 저압 전력 요금 0 원 고압 전력 요금 0 원 저압 요금 절감률 0 % 0% 이번 달 0 원 목표 절감액 : 0 원 사용전력 0 kw 저압 전력 요금 0 원 고압 전력 요금 0 원 저압 요금 절감률 0 % 0% 올해 0 원 목표 절감액 : 0 원 사용전력 0 kw 저압 전력 요금 0 원 고압 전력 요금 0 원 저압 요금 절감률 0 % 투자회수기간(ROI) - 일 &#40; - %&#41; 투자금 - 원 누적 절감액 - 원",
    "fetchedAt": "2026-08-28 12:29:53"
  },
  {
    "id": 5,
    "categoryId": 1,
    "menuName": "부하상황판",
    "pageFile": "peakPanel.html",
    "url": "https://fit.rfenms.com/peakPanel.html",
    "route": "/fit/peak-panel",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/peakPanel.html",
    "title": "부하 상황판",
    "contentLength": 2845,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/common.css?v=0.0.2",
      "./assets/css/peakPanel.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakPanel.js?v=0.0.2"
    ],
    "textContent": "부하 상황판 부하 상황판 No. 부하이름 상태 우선순위 온도(℃) 습도(%) 입력(V) 출력(V) 입력(mA) 출력(mA) - - - - - - - - - -",
    "fetchedAt": "2026-08-28 12:29:53"
  },
  {
    "id": 6,
    "categoryId": 1,
    "menuName": "피크 제어설정",
    "pageFile": "peakSet.html",
    "url": "https://fit.rfenms.com/peakSet.html",
    "route": "/fit/peak-set",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/peakSet.html",
    "title": "피크 제어설정",
    "contentLength": 5303,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/peakSet.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakSet.js?v=0.0.2"
    ],
    "textContent": "피크 제어설정 피크 제어설정 입력범위(단위) 현재값 목표전력 1~100000(kW) PCT 비율 1~65000 펄스정수 1~65000 운전모드 수동/자동 수동 자동 제어 On Delay 1~900(second) 제어 Off Delay 1~900(second) 안전 퍼센트 0~50(%) 초기제어금지 1~900(second) 알람유지시간 0~900(second) 제어방식 우선제어/순차제어 우선 순차 설정 저장",
    "fetchedAt": "2026-08-28 12:29:54"
  },
  {
    "id": 7,
    "categoryId": 1,
    "menuName": "피크 그래프",
    "pageFile": "peakHis.html",
    "url": "https://fit.rfenms.com/peakHis.html",
    "route": "/fit/peak-his",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/peakHis.html",
    "title": "피크 그래프",
    "contentLength": 9064,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/peakHis.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakHis.js?v=0.0.2"
    ],
    "textContent": "피크 그래프 피크 그래프 기록일 시간 00:15 00:30 00:45 01:00 01:15 01:30 01:45 02:00 02:15 02:30 02:45 03:00 03:15 03:30 03:45 04:00 04:15 04:30 04:45 05:00 05:15 05:30 05:45 06:00 06:15 06:30 06:45 07:00 07:15 07:30 07:45 08:00 08:15 08:30 08:45 09:00 09:15 09:30 09:45 10:00 10:15 10:30 10:45 11:00 11:15 11:30 11:45 12:00 12:15 12:30 12:45 13:00 13:15 13:30 13:45 14:00 14:15 14:30 14:45 15:00 15:15 15:30 15:45 16:00 16:15 16:30 16:45 17:00 17:15 17:30 17:45 18:00 18:15 18:30 18:45 19:00 19:15 19:30 19:45 20:00 20:15 20:30 20:45 21:00 21:15 21:30 21:45 22:00 22:15 22:30 22:45 23:00 23:15 23:30 23:45 24:00 조회",
    "fetchedAt": "2026-08-28 12:29:54"
  },
  {
    "id": 8,
    "categoryId": 1,
    "menuName": "전력 사용 보고서",
    "pageFile": "powerUsage.html",
    "url": "https://fit.rfenms.com/powerUsage.html",
    "route": "/fit/power-usage",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/powerUsage.html",
    "title": "전력 사용 보고서",
    "contentLength": 12421,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/powerUsage.css?v=0.0.2"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/powerUsage.js?v=0.0.2"
    ],
    "textContent": "전력 사용 보고서 전력 사용 보고서 구분 일별 월별 연도별 날짜 조회 엑셀로 저장 최대전력 kWh / 최대피크 kW / 일자 전체 전력량 ( kWh ) 평균 전력량 ( kWh ) 최대 전력량 ( kWh ) 최대 사용시간 피크 전력 ( kW ) 피크 시간 시간별 전력 사용량 ( kWh ) 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 전력 사용량 ( kWh ) 1월 2월 3월 4월 5월 6월 7월 8월 9월 10월 11월 12월 전체 전력량 ( kWh ) - - - - - - - - - - - - 평균 전력량 ( kWh ) - - - - - - - - - - - - 최대 전력량 ( kWh ) - - - - - - - - - - - - 1일 - - - - - - - - - - - - 연도 전체 전력량 ( kWh ) 평균 전력량 ( kWh ) 최대 전력량 ( kWh ) 월별 전력 사용량 ( kWh ) 1월 2월 3월 4월 5월 6월 7월 8월 9월 10월 11월 12월 - - - - - - - - - - - - - - - -",
    "fetchedAt": "2026-08-28 12:29:54"
  },
  {
    "id": 9,
    "categoryId": 1,
    "menuName": "피크 15분 전력보고서",
    "pageFile": "peakUsage.html",
    "url": "https://fit.rfenms.com/peakUsage.html",
    "route": "/fit/peak-usage",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/peakUsage.html",
    "title": "피크 15분 전력보고서",
    "contentLength": 5446,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/peakUsage.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakUsage.js?v=0.0.2"
    ],
    "textContent": "피크 15분 전력보고서 피크 15분 전력보고서 날짜 조회 엑셀로 저장 일자 분단위 최대수요 ( kW ) 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 - - - - - - - - - - - - - - - - - - - - - - - - - - -",
    "fetchedAt": "2026-08-28 12:29:54"
  },
  {
    "id": 10,
    "categoryId": 1,
    "menuName": "피크제어이력",
    "pageFile": "controlHis.html",
    "url": "https://fit.rfenms.com/controlHis.html",
    "route": "/fit/control-his",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/controlHis.html",
    "title": "피크제어이력",
    "contentLength": 5886,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/controlHis.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/controlHis.js?v=0.0.2"
    ],
    "textContent": "피크제어이력 피크제어이력 날짜 제어설비 설비 선택 엑셀로 다운 프린트 총 제어시간 : 0 / 총 절감액 : 0 / 최대 절감액 : 0 CID 제어설비 제어시작 제어종료 예측전력 목표전력 제어시간 절감 ( 만원 ) - - - - - - - - 1 - 5 / 5 prev 1 next",
    "fetchedAt": "2026-08-28 12:29:54"
  },
  {
    "id": 11,
    "categoryId": 1,
    "menuName": "시스템에어컨",
    "pageFile": "acp.html",
    "url": "https://fit.rfenms.com/acp.html",
    "route": "/fit/acp",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/acp.html",
    "title": "시스템에어컨 관리",
    "contentLength": 16476,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/acp.css?v=0.0.2"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/acp.js?v=0.0.2"
    ],
    "textContent": "시스템에어컨 관리 시스템에어컨 관리 시스템에어컨 설비 선택 설정 운전방식 대기중 희망운전율 0% 현재운전율 0% 통신상태 나쁨 좋음 제어동작상태 정지 (미제어) 운전 (제어) 운전모드 이름 동작상태 현재온도 설정온도 풍량 시스템에어컨 피크제어설정 에어컨 종류 피크제어 사용안함 엘지 ACP4 엘지 ACP5 삼성 DMS 2.5 접속 아이피 접속 포트 접속 아이디 접속 패스워드 내부연결 전용 제어시 희망운전율 % 제어모드 수동(피크자동제어동작안함) 자동 동작상태 수동제어 정지（미제어） 운전（제어） 확인 에어컨 온도설정 운전모드 설비이름 동작상태 현재온도 설정온도 풍량 확인",
    "fetchedAt": "2026-08-28 12:29:55"
  },
  {
    "id": 12,
    "categoryId": 1,
    "menuName": "전기 요금 비교",
    "pageFile": "ratePlan.html",
    "url": "https://fit.rfenms.com/ratePlan.html",
    "route": "/fit/rate-plan",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/ratePlan.html",
    "title": "전기 요금 비교",
    "contentLength": 8451,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/ratePlan.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/echarts.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/ratePlan.js?v=0.0.2"
    ],
    "textContent": "전기 요금 비교 전기 요금 비교 요금제1 요금제 선택 산업용(을)고압A 선택I 산업용(을)고압A 선택II 산업용(을)고압A 선택III 산업용(을)고압B 선택I 산업용(을)고압B 선택II 산업용(을)고압B 선택III 산업용(을)고압C 선택I 산업용(을)고압C 선택II 산업용(을)고압C 선택III 산업용(갑)II고압A 선택I 산업용(갑)II고압A 선택II 산업용(갑)II고압B 선택I 산업용(갑)II고압B 선택II 산업용(갑)I 저압 요금제2 요금제 선택 산업용(을)고압A 선택I 산업용(을)고압A 선택II 산업용(을)고압A 선택III 산업용(을)고압B 선택I 산업용(을)고압B 선택II 산업용(을)고압B 선택III 산업용(을)고압C 선택I 산업용(을)고압C 선택II 산업용(을)고압C 선택III 산업용(갑)II고압A 선택I 산업용(갑)II고압A 선택II 산업용(갑)II고압B 선택I 산업용(갑)II고압B 선택II 산업용(갑)I 저압 계절 부하구분 요금제1 요금제2 절감액 절감률 여름철 경부하 0 0 0 0 중부하 0 0 0 0 최대부하 0 0 0 0 봄·가을철 경부하 0 0 0 0 중부하 0 0 0 0 최대부하 0 0 0 0 겨울철 경부하 0 0 0 0 중부하 0 0 0 0 최대부하 0 0 0 0 평균 0 0 0 0",
    "fetchedAt": "2026-08-28 12:29:55"
  },
  {
    "id": 13,
    "categoryId": 1,
    "menuName": "저압 절감 분석",
    "pageFile": "reduce.html",
    "url": "https://fit.rfenms.com/reduce.html",
    "route": "/fit/reduce",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/reduce.html",
    "title": "저압 절감 분석",
    "contentLength": 8856,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/reduce.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/echarts.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reduce.js?v=0.0.2"
    ],
    "textContent": "저압 절감 분석 저압 절감 분석 시간별 일자별 월별 조회 기본요금 포함 검침일 적용 저압 절감 금액 -% 목표 절감 금액 - 원 저압 절감 금액 - 원 평균 절감 금액 - 원 평균 절감률 - % 일시 사용전력량(kWh) 고압 전력 요금 저압 전력 요금 절감 금액 절감률 저압 전력 요금 저압 전력 요금 - 원 사용 전력량 - kWh 최고 전력 요금 - 원 평균 사용 전력량 - kWh 평균 저압 전력 요금 - 원 직전 동일 기간 대비 저압 전력 요금 - 원 사용 전력량 - kWh 최고 전력 요금 - 원 평균 절감 금액 - 원 평균 절감률 - %",
    "fetchedAt": "2026-08-28 12:29:55"
  },
  {
    "id": 14,
    "categoryId": 1,
    "menuName": "저압 절감 보고서",
    "pageFile": "report.html",
    "url": "https://fit.rfenms.com/report.html",
    "route": "/fit/report",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/report.html",
    "title": "저압 절감 보고서",
    "contentLength": 8200,
    "styles": [
      "./assets/css/lib/tom-select.css",
      "./assets/css/lib/tui-date-picker.css",
      "assets/css/common.css?v=0.0.2",
      "./assets/css/report.css?v=0.0.2"
    ],
    "scripts": [
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/tom-select.complete.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/report.js?v=0.0.5"
    ],
    "textContent": "저압 절감 보고서 저압 절감 보고서 전력타입 - 기본요금단가 - 최근 5개년 피크 - kw / - 년 누적 절감 요금 저압 전력 요금 고압 전력 요금 평균 절감률 - % 일간 평균 절감액 - 원 월간 평균 절감액 - 원 연간 평균 절감액 - 원 제안서 A 제안서 B (팩토링 선취) 사업 타당성 검토 제안서 C (팩토링 후취) 사업 타당성 검토 기간 &#126; 조회 엑셀로 저장 날짜 요금적용전력&#40;kW&#41; 사용전력량&#40;kWh&#41; 전력 요금 &#40;고압&#41; 전력 요금 &#40;저압&#41; 절감액 기본요금 전력량요금+a 소계 기본요금 전력량요금+a 소계 데이터가 없습니다.",
    "fetchedAt": "2026-08-28 12:29:55"
  },
  {
    "id": 15,
    "categoryId": 2,
    "menuName": "로그인",
    "pageFile": "login.html",
    "url": "https://fit.rfenms.com/login.html",
    "route": "/fit/login",
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/login.html",
    "title": "한국미래에너지",
    "contentLength": 2110,
    "styles": [
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/login.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/jquery.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/login.js?v=0.0.2"
    ],
    "textContent": "한국미래에너지 한전수전합리화 플랫폼 Login 아이디저장 LOGIN",
    "fetchedAt": "2026-08-28 12:29:55"
  },
  {
    "id": 16,
    "categoryId": 3,
    "menuName": "좌측 메뉴",
    "pageFile": "include/leftnav.html",
    "url": "https://fit.rfenms.com/include/leftnav.html",
    "route": null,
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/include/leftnav.html",
    "title": "",
    "contentLength": 4019,
    "styles": [],
    "scripts": [],
    "textContent": "통합관제 업체관리 한전데이터 수집 피크상태 부하상황판 피크 제어설정 피크 그래프 전력 사용 보고서 피크 15분 전력보고서 피크제어이력 시스템에어컨 전기 요금 비교 저압 절감 분석 저압 절감 보고서",
    "fetchedAt": "2026-08-28 12:29:56"
  },
  {
    "id": 17,
    "categoryId": 3,
    "menuName": "상단바",
    "pageFile": "include/top.html",
    "url": "https://fit.rfenms.com/include/top.html",
    "route": null,
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/include/top.html",
    "title": "",
    "contentLength": 2918,
    "styles": [],
    "scripts": [],
    "textContent": "주의요함 이번주는 피크관리에 각별한 관심이 필요합니다! 관심필요 이번주 피크 횟수가 평균을 초과하였습니다. 보통 이번주 피크현황이 안정적입니다. 좋아요! 이번주 에너지 사용이 원활합니다. 새로고침 환경설정 사용자관리 알람설정 게이트웨이 관리 복합제어기 관리 시퀀스제어 RTU관리 모드버스 계측 실시간데이터 통신상태 불량 로그아웃",
    "fetchedAt": "2026-08-28 12:29:56"
  },
  {
    "id": 18,
    "categoryId": 3,
    "menuName": "대시보드 위젯",
    "pageFile": "include/widget.html",
    "url": "https://fit.rfenms.com/include/widget.html",
    "route": null,
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/login.html",
    "title": "한국미래에너지",
    "contentLength": 2110,
    "styles": [
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/login.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/jquery.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/login.js?v=0.0.2"
    ],
    "textContent": "한국미래에너지 한전수전합리화 플랫폼 Login 아이디저장 LOGIN",
    "fetchedAt": "2026-08-28 12:29:56"
  },
  {
    "id": 19,
    "categoryId": 3,
    "menuName": "푸터",
    "pageFile": "include/footer.html",
    "url": "https://fit.rfenms.com/include/footer.html",
    "route": null,
    "httpStatus": 200,
    "finalUrl": "https://fit.rfenms.com/include/footer.html",
    "title": "",
    "contentLength": 5587,
    "styles": [],
    "scripts": [],
    "textContent": "팝업창 타이틀 들어가는 곳 설정 등 팝업창의 디자인은 보더라인과 드롭쉐도우를 적용하고 있습니다. 항목 내용 테이블 테이블 사용시 예제 취소 저장 알림 최적화는 필수 입니다. Cancel OK 고객정보 업체명 고객번호 0000000000 청구년월 0000년 00일 정기검침일 00일 요금적용전력 0 ㎾ 전력량요금 0 원 기본요금 0 원 전기요금계 0 원 청구요금 0 원 경부하사용량 0 ㎾h 중부하사용량 0 ㎾h 최대부하사용량 0 ㎾h 진상역률 0 % 지상역률 0 %",
    "fetchedAt": "2026-08-28 12:29:56"
  }
];

/** 라우트가 있는 페이지만 (include 파샬 제외) */
export const FIT_MOCK_ROUTED_PAGES: readonly FitMockPage[] = FIT_MOCK_PAGES.filter(
  (page) => page.route !== null,
);

export function findFitMockPage(pageFile: string): FitMockPage | undefined {
  return FIT_MOCK_PAGES.find((page) => page.pageFile === pageFile);
}

export function findFitMockPageByRoute(route: string): FitMockPage | undefined {
  return FIT_MOCK_PAGES.find((page) => page.route === route);
}
