/**
 * AUTO-GENERATED by scripts/build-mock-db.mjs — 직접 수정하지 말 것.
 * 원본: data/pages.db (파이어크롤 수집, 2026-08-27T19:50:50.721Z)
 * 재생성: node scripts/build-mock-db.mjs
 */

export interface MockCategory {
  id: number;
  ord: number;
  name: string;
  disabled: boolean;
}

export interface MockPage {
  id: number;
  categoryId: number;
  menuName: string;
  pageFile: string;
  url: string;
  menuDisabled: boolean;
  expectedTitle: string;
  httpStatus: number;
  finalUrl: string;
  title: string;
  contentLength: number;
  styles: string[];
  scripts: string[];
  textPreview: string;
  fetchedAt: string;
}

export interface MockFetchSummary {
  categories: number;
  pagesTotal: number;
  pagesOk: number;
  failures: string[];
  fetchedAt: string;
}

export const MOCK_FETCH_SUMMARY: MockFetchSummary = {
  "categories": 13,
  "pagesTotal": 45,
  "pagesOk": 45,
  "failures": [],
  "fetchedAt": "2026-08-27T19:50:50.721Z"
};

export const MOCK_CATEGORIES: MockCategory[] = [
  {
    "id": 1,
    "ord": 1,
    "name": "통합관제",
    "disabled": true
  },
  {
    "id": 2,
    "ord": 2,
    "name": "업체관리",
    "disabled": true
  },
  {
    "id": 3,
    "ord": 3,
    "name": "대시보드",
    "disabled": false
  },
  {
    "id": 4,
    "ord": 4,
    "name": "컨설팅",
    "disabled": true
  },
  {
    "id": 5,
    "ord": 5,
    "name": "피크관리",
    "disabled": false
  },
  {
    "id": 6,
    "ord": 6,
    "name": "전력사용량",
    "disabled": false
  },
  {
    "id": 7,
    "ord": 7,
    "name": "절감효과",
    "disabled": false
  },
  {
    "id": 8,
    "ord": 8,
    "name": "계통감시",
    "disabled": false
  },
  {
    "id": 9,
    "ord": 9,
    "name": "설비관리",
    "disabled": false
  },
  {
    "id": 10,
    "ord": 10,
    "name": "비교분석",
    "disabled": false
  },
  {
    "id": 11,
    "ord": 11,
    "name": "보고서",
    "disabled": false
  },
  {
    "id": 12,
    "ord": 12,
    "name": "인증",
    "disabled": false
  },
  {
    "id": 13,
    "ord": 13,
    "name": "include (내부 파일)",
    "disabled": false
  }
];

export const MOCK_PAGES: MockPage[] = [
  {
    "id": 1,
    "categoryId": 1,
    "menuName": "통합관제",
    "pageFile": "stat.html",
    "url": "https://watt.rfenms.com/stat.html",
    "menuDisabled": false,
    "expectedTitle": "통합관제",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/stat.html",
    "title": "통합관제",
    "contentLength": 76599,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/stat.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "//dapi.kakao.com/v2/maps/sdk.js?appkey=d2adb52204965f533f0c70a2c73b5553&libraries=services",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/stat.js?v=0.0.2"
    ],
    "textPreview": "통합관제 피크현황 피크초과 0 피크근접 0 피크안정 0 전체제어 0 일부제어 0 제어안함 0 긴급 0 검토 0 피크초과 피크근접 제어중 긴급 검토 초기화 피크율 높은순 피크율 낮은순 수요시간 마감순 수요시간 시작순 제어기기 많은순 제어기기 적은순 정확도 높은순 정확도 낮은순 업체명 피크상태 제어상태 제어모드 요금적용전력 목표전력비 예측/목표전력 피크율/소요시간 정확도 kW kW % kW kW - % % kW kW % kW kW",
    "fetchedAt": "2026-08-28 04:50:43"
  },
  {
    "id": 2,
    "categoryId": 2,
    "menuName": "업체관리",
    "pageFile": "firm.html",
    "url": "https://watt.rfenms.com/firm.html",
    "menuDisabled": false,
    "expectedTitle": "업체관리",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/firm.html",
    "title": "업체관리",
    "contentLength": 23626,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/firm.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "//dapi.kakao.com/v2/maps/sdk.js?appkey=d2adb52204965f533f0c70a2c73b5553&libraries=services",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/firm.js?v=0.0.4"
    ],
    "textPreview": "업체관리 업체관리 1 - 5 / 5 추가 엑셀 프린트 요금표 한전수집 서비스상태 선택 EMS 피크 저압 완료 EMS 준비 피크 준비 저압 준비 EMS 제안 피크 제안 저압 제안 ID 이름 전력타입 한전고객번호 EOI PCT 최근전력 목표전력 운전모드 제어방식 활성 서비스 메모 - - - - - - - - - - - - - 1 - 5 / 5 prev 1 next 업체관리 이름 기상청지점 선택 서울 부산 대구 강화 백령도 인천 광",
    "fetchedAt": "2026-08-28 04:50:43"
  },
  {
    "id": 3,
    "categoryId": 3,
    "menuName": "대시보드 위젯",
    "pageFile": "main.html",
    "url": "https://watt.rfenms.com/main.html",
    "menuDisabled": false,
    "expectedTitle": "대시보드",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/main.html",
    "title": "대시보드",
    "contentLength": 1549,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/main.css?v=0.0.2"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/echarts.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.2",
      "./assets/js/main.js?v=0.0.5"
    ],
    "textPreview": "대시보드",
    "fetchedAt": "2026-08-28 04:50:43"
  },
  {
    "id": 4,
    "categoryId": 3,
    "menuName": "대시보드 전력메인",
    "pageFile": "wattMain.html",
    "url": "https://watt.rfenms.com/wattMain.html",
    "menuDisabled": false,
    "expectedTitle": "전력 대시보드",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/wattMain.html",
    "title": "전력 대시보드",
    "contentLength": 33897,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/wattMain.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/lib/echarts.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/wattMain.js?v=0.0.2"
    ],
    "textPreview": "전력 대시보드 안정 근접 초과 실시간 PEAK 전력 00,000 kW / 시간대 00:00 오늘의 PEAK ▲ 00.0% (+000) 전주 동일 시간 대비 00:00 / 15:00 실시간 전력 사용량 00,000 kWh / ~ 00:00 오늘의 사용량 ▲ 00.0% (+000) 전주 동일 시간 대비 1시간당 사용량 0 kWh 전주 동일시간 대비 ▲ 00.0% (+000) 경부하 중부하 최대부하 00:00 / 00:00 0000",
    "fetchedAt": "2026-08-28 04:50:43"
  },
  {
    "id": 5,
    "categoryId": 3,
    "menuName": "태양광 대시보드",
    "pageFile": "solar.html",
    "url": "https://watt.rfenms.com/solar.html",
    "menuDisabled": false,
    "expectedTitle": "대시보드 - 태양광 대시보드",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/solar.html",
    "title": "대시보드 - 태양광 대시보드",
    "contentLength": 8937,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/solar.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/echarts.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/solar.js?v=0.0.1"
    ],
    "textPreview": "대시보드 - 태양광 대시보드 태양광 대시보드 그룹 전체 시간단위 시간대별 일별 월별 날짜 조회 엑셀로 다운 설비 설비 목록 준비 날짜 조회 저장 오늘 발전량 - kWh 오늘 발전시간 - h 어제 발전량 - kWh 어제 발전시간 - h 당월 발전량 - kWh 당월 발전시간 - h 올해 발전량 - kWh 올해 발전시간 - h",
    "fetchedAt": "2026-08-28 04:50:43"
  },
  {
    "id": 6,
    "categoryId": 4,
    "menuName": "컨설팅",
    "pageFile": "consulting.html",
    "url": "https://watt.rfenms.com/consulting.html",
    "menuDisabled": false,
    "expectedTitle": "한국미래에너지",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/login.html",
    "title": "한국미래에너지",
    "contentLength": 2114,
    "styles": [
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/login.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/jquery.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/login.js?v=0.0.2"
    ],
    "textPreview": "한국미래에너지 ABC 에너지 통합관제 시스템 Login 아이디저장 LOGIN",
    "fetchedAt": "2026-08-28 04:50:44"
  },
  {
    "id": 7,
    "categoryId": 5,
    "menuName": "피크상태",
    "pageFile": "peak.html",
    "url": "https://watt.rfenms.com/peak.html",
    "menuDisabled": false,
    "expectedTitle": "피크관리 - 피크상태",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/peak.html",
    "title": "피크관리 - 피크상태",
    "contentLength": 12698,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/peak.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peak.js?v=0.0.2"
    ],
    "textPreview": "피크관리 - 피크상태 피크상태 검침일 -일 검침일 기준 적용 데이터정확도 -% 알림 00% 00:00 / 15:00 계기시간 00:00:00 시간차 0 초 예측 전력 0 목표 전력 0 현재 전력 0 기준 전력 0 순간 전력 0 MODE 자동/우선순위 제어를 요청하였습니다. OFF 제어 Wait... 0% 이번달 요금적용전력 - kW 0000-00-00 00:00 오늘최대수요 중부하, 최대부하만 적용 - kW 0000-00-00",
    "fetchedAt": "2026-08-28 04:50:44"
  },
  {
    "id": 8,
    "categoryId": 5,
    "menuName": "부하상황판",
    "pageFile": "peakPanel.html",
    "url": "https://watt.rfenms.com/peakPanel.html",
    "menuDisabled": false,
    "expectedTitle": "피크관리 - 부하 상황판",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/peakPanel.html",
    "title": "피크관리 - 부하 상황판",
    "contentLength": 2918,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/peakPanel.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakPanel.js?v=0.0.2"
    ],
    "textPreview": "피크관리 - 부하 상황판 부하 상황판 No. 부하이름 상태 우선순위 온도(℃) 습도(%) 입력(V) 출력(V) 입력(mA) 출력(mA) - - - - - - - - - -",
    "fetchedAt": "2026-08-28 04:50:44"
  },
  {
    "id": 9,
    "categoryId": 5,
    "menuName": "피크 제어설정",
    "pageFile": "peakSet.html",
    "url": "https://watt.rfenms.com/peakSet.html",
    "menuDisabled": false,
    "expectedTitle": "피크관리 - 피크 제어설정",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/peakSet.html",
    "title": "피크관리 - 피크 제어설정",
    "contentLength": 5473,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/peakSet.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakSet.js?v=0.0.2"
    ],
    "textPreview": "피크관리 - 피크 제어설정 피크 제어설정 입력범위(단위) 현재값 목표전력 1~100000(kW) PCT 비율 1~65000 펄스정수 1~65000 운전모드 수동/자동 수동 자동 제어 On Delay 1~900(second) 제어 Off Delay 1~900(second) 안전 퍼센트 0~50(%) 초기제어금지 1~900(second) 알람유지시간 0~900(second) 제어방식 우선제어/순차제어 우선 순차 설정 저장",
    "fetchedAt": "2026-08-28 04:50:44"
  },
  {
    "id": 10,
    "categoryId": 5,
    "menuName": "피크 그래프",
    "pageFile": "peakHis.html",
    "url": "https://watt.rfenms.com/peakHis.html",
    "menuDisabled": false,
    "expectedTitle": "피크관리 - 피크 그래프",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/peakHis.html",
    "title": "피크관리 - 피크 그래프",
    "contentLength": 9234,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/peakHis.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakHis.js?v=0.0.2"
    ],
    "textPreview": "피크관리 - 피크 그래프 피크 그래프 기록일 시간 00:15 00:30 00:45 01:00 01:15 01:30 01:45 02:00 02:15 02:30 02:45 03:00 03:15 03:30 03:45 04:00 04:15 04:30 04:45 05:00 05:15 05:30 05:45 06:00 06:15 06:30 06:45 07:00 07:15 07:30 07:45 08:00 08:15 08:30 08:45 09",
    "fetchedAt": "2026-08-28 04:50:44"
  },
  {
    "id": 11,
    "categoryId": 5,
    "menuName": "전력 사용 보고서",
    "pageFile": "powerUsage.html",
    "url": "https://watt.rfenms.com/powerUsage.html",
    "menuDisabled": false,
    "expectedTitle": "피크관리 - 전력사용보고서",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/powerUsage.html",
    "title": "피크관리 - 전력사용보고서",
    "contentLength": 12571,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/powerUsage.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/powerUsage.js?v=0.0.2"
    ],
    "textPreview": "피크관리 - 전력사용보고서 전력 사용 보고서 구분 일별 월별 연도별 날짜 조회 엑셀로 저장 최대전력 kWh / 최대피크 kW / 일자 전체 전력량 ( kWh ) 평균 전력량 ( kWh ) 최대 전력량 ( kWh ) 최대 사용시간 피크 전력 ( kW ) 피크 시간 시간별 전력 사용량 ( kWh ) 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 - - - - - -",
    "fetchedAt": "2026-08-28 04:50:44"
  },
  {
    "id": 12,
    "categoryId": 5,
    "menuName": "피크 15분 전력보고서",
    "pageFile": "peakUsage.html",
    "url": "https://watt.rfenms.com/peakUsage.html",
    "menuDisabled": false,
    "expectedTitle": "피크관리 - 피크 15분 전력보고서",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/peakUsage.html",
    "title": "피크관리 - 피크 15분 전력보고서",
    "contentLength": 5592,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/peakUsage.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/peakUsage.js?v=0.0.2"
    ],
    "textPreview": "피크관리 - 피크 15분 전력보고서 피크 15분 전력보고서 날짜 조회 엑셀로 저장 일자 분단위 최대수요 ( kW ) 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 - - - - - - - - - - - - - - - - - - - - - - - - - - -",
    "fetchedAt": "2026-08-28 04:50:45"
  },
  {
    "id": 13,
    "categoryId": 5,
    "menuName": "피크제어이력",
    "pageFile": "controlHis.html",
    "url": "https://watt.rfenms.com/controlHis.html",
    "menuDisabled": false,
    "expectedTitle": "피크관리 - 피크제어이력",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/controlHis.html",
    "title": "피크관리 - 피크제어이력",
    "contentLength": 6056,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/controlHis.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/controlHis.js?v=0.0.3"
    ],
    "textPreview": "피크관리 - 피크제어이력 피크제어이력 날짜 제어설비 설비 선택 엑셀로 다운 프린트 총 제어시간 : 0 / 총 절감액 : 0 / 최대 절감액 : 0 CID 제어설비 제어시작 제어종료 예측전력 목표전력 제어시간 절감 ( 만원 ) - - - - - - - - 1 - 5 / 5 prev 1 next",
    "fetchedAt": "2026-08-28 04:50:45"
  },
  {
    "id": 14,
    "categoryId": 5,
    "menuName": "시스템에어컨",
    "pageFile": "acp.html",
    "url": "https://watt.rfenms.com/acp.html",
    "menuDisabled": false,
    "expectedTitle": "시스템에어컨 관리",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/acp.html",
    "title": "시스템에어컨 관리",
    "contentLength": 16651,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/acp.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/acp.js?v=0.0.2"
    ],
    "textPreview": "시스템에어컨 관리 시스템에어컨 관리 시스템에어컨 설비 선택 설정 운전방식 대기중 희망운전율 0% 현재운전율 0% 통신상태 나쁨 좋음 제어동작상태 정지 (미제어) 운전 (제어) 운전모드 이름 동작상태 현재온도 설정온도 풍량 시스템에어컨 피크제어설정 에어컨 종류 피크제어 사용안함 엘지 ACP4 엘지 ACP5 삼성 DMS 2.5 접속 아이피 접속 포트 접속 아이디 접속 패스워드 내부연결 전용 제어시 희망운전율 % 제어모드 수동(피크",
    "fetchedAt": "2026-08-28 04:50:45"
  },
  {
    "id": 15,
    "categoryId": 6,
    "menuName": "전력사용량 보기",
    "pageFile": "powerPage.html",
    "url": "https://watt.rfenms.com/powerPage.html",
    "menuDisabled": false,
    "expectedTitle": "전력사용량 - 전력사용량 보기",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/powerPage.html",
    "title": "전력사용량 - 전력사용량 보기",
    "contentLength": 130138,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/powerPage.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/powerPage.js?v=0.0.2"
    ],
    "textPreview": "전력사용량 - 전력사용량 보기 전력사용량 보기 00:00:00 0000. 00. 00. (일) 경부하 중간부하 최대부하 일일 설비별 사용요금 경부하 0 원 중간부하 0 원 최대부하 0 원 전체 0 원 시간단위 시간대별 일별 월별 연도별 요일별 설비 설비 목록 준비 날짜 15분 60분 조회 엑셀로 다운 1분단위 설비 설비 목록 준비 날짜 조회 저장 설비 설비 목록 준비 날짜 조회 저장 설비 설비 목록 준비 조회 저장 설비 설비 ",
    "fetchedAt": "2026-08-28 04:50:45"
  },
  {
    "id": 16,
    "categoryId": 6,
    "menuName": "소비량 예측",
    "pageFile": "wattPrediction.html",
    "url": "https://watt.rfenms.com/wattPrediction.html",
    "menuDisabled": false,
    "expectedTitle": "전력사용량 - 소비량 예측",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/wattPrediction.html",
    "title": "전력사용량 - 소비량 예측",
    "contentLength": 9840,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/wattPrediction.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/wattPrediction.js?v=0.0.2"
    ],
    "textPreview": "전력사용량 - 소비량 예측 소비량 예측 설비 설비 목록 준비 엑셀 샘플받기 파일등록 조회 구분 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 생산량 - - - - - - - - - - - - - - - - - - - - 원자재 - - - - - - - - - - - - - - - - - - - - 예측전력 - - - - - - - - - - - - - - - - - - - - 전력량",
    "fetchedAt": "2026-08-28 04:50:45"
  },
  {
    "id": 17,
    "categoryId": 7,
    "menuName": "절감효과",
    "pageFile": "enpi.html",
    "url": "https://watt.rfenms.com/enpi.html",
    "menuDisabled": false,
    "expectedTitle": "절감효과",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/enpi.html",
    "title": "절감효과",
    "contentLength": 12237,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/enpi.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/enpi.js?v=0.0.2"
    ],
    "textPreview": "절감효과 절감효과 에너지 사용량 0.00 toe 지난주 대비 - 지난달 대비 - 지난해 대비 - 에너지 절감량 0.00 toe 누적 개선율 0.00 % 에너지 절감비용 0.00 만원 온실가스 절감량 0.00 tCo₂ 날짜 조회 샘플받기 파일등록 날짜 에너지원 에너지원 단위환산 탄소배출 단위환산 독립변수 전력(소비기준) 단위 전력(소비기준) 단위 전력(소비기준) 단위 생산량 HDD CDD 0000-00-00 No. 에너지원 환산",
    "fetchedAt": "2026-08-28 04:50:45"
  },
  {
    "id": 18,
    "categoryId": 8,
    "menuName": "계통감시",
    "pageFile": "monit.html",
    "url": "https://watt.rfenms.com/monit.html",
    "menuDisabled": false,
    "expectedTitle": "계통감시",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/monit.html",
    "title": "계통감시",
    "contentLength": 1738,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/monit.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/monit.js?v=0.0.2"
    ],
    "textPreview": "계통감시",
    "fetchedAt": "2026-08-28 04:50:46"
  },
  {
    "id": 19,
    "categoryId": 8,
    "menuName": "공정별 에너지 계통",
    "pageFile": "energyMonit.html",
    "url": "https://watt.rfenms.com/energyMonit.html",
    "menuDisabled": false,
    "expectedTitle": "공정별 에너지 계통",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/energyMonit.html",
    "title": "공정별 에너지 계통",
    "contentLength": 11245,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/energyMonit.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/energyMonit.js?v=0.0.2"
    ],
    "textPreview": "공정별 에너지 계통 공정별 에너지 계통 등록된 데이터가 없습니다. 공정분류 변경 변경이력 조회 에너지원 전체 전력 도시가스 용수 기간 ~ 조회 엑셀로 다운 간략히보기 전력 - kWh 도시가스 - Nm³ 용수 - ton 변경이력 조회 ~ 조회 날짜 시간 담당자 항목 변경내용 변경이력이 없습니다. 0 - 0 / 0 prev 1 next",
    "fetchedAt": "2026-08-28 04:50:46"
  },
  {
    "id": 20,
    "categoryId": 9,
    "menuName": "제어설비목록",
    "pageFile": "techSettings.html",
    "url": "https://watt.rfenms.com/techSettings.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 제어설비목록",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/techSettings.html",
    "title": "설비관리 - 제어설비목록",
    "contentLength": 4554,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/techSettings.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/techSettings.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 제어설비목록 제어설비목록 1 - 5 / 5 엑셀로 다운 프린트 CID 설비명 상태 전압 전류 온도 현재값 최적화제어 제어시간(시) 절감금액(만) - - - - - - - - - - 1 - 5 / 5 prev 1 next",
    "fetchedAt": "2026-08-28 04:50:46"
  },
  {
    "id": 21,
    "categoryId": 9,
    "menuName": "주요설비 이용률",
    "pageFile": "techUsage.html",
    "url": "https://watt.rfenms.com/techUsage.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 주요설비 이용률",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/techUsage.html",
    "title": "설비관리 - 주요설비 이용률",
    "contentLength": 3369,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/techUsage.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/techUsage.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 주요설비 이용률 주요설비 이용률 MAIN 기간 ~ 조회",
    "fetchedAt": "2026-08-28 04:50:46"
  },
  {
    "id": 22,
    "categoryId": 9,
    "menuName": "주요설비 부하율",
    "pageFile": "techOver.html",
    "url": "https://watt.rfenms.com/techOver.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 주요설비 부하율",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/techOver.html",
    "title": "설비관리 - 주요설비 부하율",
    "contentLength": 3504,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/techOver.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/techOver.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 주요설비 부하율 주요설비 부하율 MAIN 기간 ~ 조회",
    "fetchedAt": "2026-08-28 04:50:46"
  },
  {
    "id": 23,
    "categoryId": 9,
    "menuName": "설비 제어",
    "pageFile": "techTree.html",
    "url": "https://watt.rfenms.com/techTree.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 설비 제어",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/techTree.html",
    "title": "설비관리 - 설비 제어",
    "contentLength": 5932,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/techTree.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/techTree.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 설비 제어 설비 제어 설비관리 날짜 및 시간 조회 개별 설비설정 그룹이름 설비이름 우선순위 기본설정온도(°C) 피크제어수치(%) 게이트웨이 노드번호 채널번호 확인 취소",
    "fetchedAt": "2026-08-28 04:50:46"
  },
  {
    "id": 24,
    "categoryId": 9,
    "menuName": "최적화 제어",
    "pageFile": "techPlan.html",
    "url": "https://watt.rfenms.com/techPlan.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 최적화 제어",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/techPlan.html",
    "title": "설비관리 - 최적화 제어",
    "contentLength": 15479,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/techPlan.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/techPlan.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 최적화 제어 최적화 제어 스케줄등록 엑셀로 다운 프린트 ID 제어이름 활성 제어기간 계절제어 요일제어 기간제어 시간제어 분단위제어 온도조건[출력] 적용설비 - - - - - - - - - - - 1 - 5 / 5 prev 1 next 설비제어 제어이름 제어시작 제어복제 제어 선택 제어종료 제어활성 활성 제어중지 계절선택 봄 여름 가을 겨울 요일선택 월 화 수 목 금 토 일 기간제어 요일 월요일 화요일 수요일 목요일",
    "fetchedAt": "2026-08-28 04:50:47"
  },
  {
    "id": 25,
    "categoryId": 9,
    "menuName": "최적화 제어이력",
    "pageFile": "techHis.html",
    "url": "https://watt.rfenms.com/techHis.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 최적화 제어이력",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/techHis.html",
    "title": "설비관리 - 최적화 제어이력",
    "contentLength": 5355,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/techHis.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/techHis.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 최적화 제어이력 최적화 제어이력 제어설비 설비 선택 날짜 조회 엑셀로 다운 프린트 CID 제어설비 제어방법 제어시작 제어종료 제어시점 온도 종료시점 온도 제어시점 출력 종료시점 출력 제어설정 제어시간 절감전력 - - - - - - - - - - - - 1 - 5 / 5 prev 1 next",
    "fetchedAt": "2026-08-28 04:50:47"
  },
  {
    "id": 26,
    "categoryId": 9,
    "menuName": "콤프레셔",
    "pageFile": "compressor.html",
    "url": "https://watt.rfenms.com/compressor.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 콤프레셔",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/compressor.html",
    "title": "설비관리 - 콤프레셔",
    "contentLength": 22303,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/report.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/compressor.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 콤프레셔 콤프레셔 설비 설비 목록 준비 날짜 일간 주간 월간 조회 저장 시간 사용량( kWh ) 최대수요( kW ) 압력 온도 RPM 00:00 - - - - - 00:15 - - - - - 00:30 - - - - - 00:45 - - - - - 01:00 - - - - - 01:15 - - - - - 01:30 - - - - - 01:45 - - - - - 02:00 - - - - - 02:15 - - - - ",
    "fetchedAt": "2026-08-28 04:50:47"
  },
  {
    "id": 27,
    "categoryId": 9,
    "menuName": "온도",
    "pageFile": "thermos.html",
    "url": "https://watt.rfenms.com/thermos.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 온도",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/thermos.html",
    "title": "설비관리 - 온도",
    "contentLength": 5447,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/solar.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/echarts.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/thermos.js?v=0.0.1"
    ],
    "textPreview": "설비관리 - 온도 온도 시간단위 15분 일별 날짜 조회 엑셀로 다운 설비 설비 목록 준비 날짜 조회 저장",
    "fetchedAt": "2026-08-28 04:50:47"
  },
  {
    "id": 28,
    "categoryId": 9,
    "menuName": "가스 사용량",
    "pageFile": "gasReports.html",
    "url": "https://watt.rfenms.com/gasReports.html",
    "menuDisabled": false,
    "expectedTitle": "가스사용량",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/gasReports.html",
    "title": "가스사용량",
    "contentLength": 3296,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/gasReports.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/gasReports.js?v=0.0.1"
    ],
    "textPreview": "가스사용량 가스사용량 구분 시간대별 일별 월별 설비 설비 목록 준비 날짜 조회 저장",
    "fetchedAt": "2026-08-28 04:50:47"
  },
  {
    "id": 29,
    "categoryId": 9,
    "menuName": "냉난방 제어",
    "pageFile": "techFrozen.html",
    "url": "https://watt.rfenms.com/techFrozen.html",
    "menuDisabled": false,
    "expectedTitle": "설비관리 - 냉난방 제어",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/techFrozen.html",
    "title": "설비관리 - 냉난방 제어",
    "contentLength": 7058,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1",
      "./assets/css/techFrozen.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/techFrozen.js?v=0.0.2"
    ],
    "textPreview": "설비관리 - 냉난방 제어 냉난방 제어 냉방 난방 도면그룹 도면그룹 선택 분류 이름 현재상태 전압 전류 제어모드 순위 냉난방 제어설정 수동제어 설정 ON OFF 제어모드 변경 수동 자동 우선순위 제어요청 진행중입니다. 확인",
    "fetchedAt": "2026-08-28 04:50:47"
  },
  {
    "id": 30,
    "categoryId": 9,
    "menuName": "PLC 제어 관리",
    "pageFile": "plc.html",
    "url": "https://watt.rfenms.com/plc.html",
    "menuDisabled": false,
    "expectedTitle": "PLC 제어 관리",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/plc.html",
    "title": "PLC 제어 관리",
    "contentLength": 6534,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/deskLib.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "assets/js/plc.js?v=0.0.2"
    ],
    "textPreview": "PLC 제어 관리 PLC 제어 관리 추가 모니터링 이름 읽기주소 제어주소 온도범위(°C) 제어값(Hz) 제어딜레이(s) 활성 데이터가 없습니다. 1 - 5 / 5 prev 1 next PLC 제어 관리 활성 비활성 활성 이름 온도주소 온도소수점단위 읽기주소 제어주소 소수점단위 제어 딜레이 제어조건 취소 삭제 확인",
    "fetchedAt": "2026-08-28 04:50:48"
  },
  {
    "id": 31,
    "categoryId": 10,
    "menuName": "목표대비 비교분석",
    "pageFile": "kpi.html",
    "url": "https://watt.rfenms.com/kpi.html",
    "menuDisabled": false,
    "expectedTitle": "비교분석 - 목표대비 비교분석",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/kpi.html",
    "title": "비교분석 - 목표대비 비교분석",
    "contentLength": 9635,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/kpi.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/kpi.js?v=0.0.2"
    ],
    "textPreview": "비교분석 - 목표대비 비교분석 목표대비 비교분석 파일업로드 생산량 전체생산량 조업시간 생산원가 매출액 목표량 MAIN 기간 ~ 시간별 일별 월별 연별 전력량 kWh 최대수요 kW 전류 온실가스배출량 kgCO₂ 생산량대비(설비효율분석) 조업시간대비(시간당설비효율분석) 매출액대비(원단위설비효율) 목표량대비(전력소비효율) 막대 라인 조회 엑셀로 다운 시간 - 생산량 정보입력 기간 조회 엑셀 다운 파일 등록 파일 저장",
    "fetchedAt": "2026-08-28 04:50:48"
  },
  {
    "id": 32,
    "categoryId": 10,
    "menuName": "개별계측기관리",
    "pageFile": "sensor.html",
    "url": "https://watt.rfenms.com/sensor.html",
    "menuDisabled": false,
    "expectedTitle": "비교분석 - 개별계측기관리",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/sensor.html",
    "title": "비교분석 - 개별계측기관리",
    "contentLength": 8896,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/sensor.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/sensor.js?v=0.0.2"
    ],
    "textPreview": "비교분석 - 개별계측기관리 개별계측기관리 MAIN 계측기이름 구분 R S T 단위 - - - - - - - - - - 구분 단위 - - - - - - - - - -",
    "fetchedAt": "2026-08-28 04:50:48"
  },
  {
    "id": 33,
    "categoryId": 10,
    "menuName": "전력사용현황",
    "pageFile": "reportFine.html",
    "url": "https://watt.rfenms.com/reportFine.html",
    "menuDisabled": false,
    "expectedTitle": "전력사용현황",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/reportFine.html",
    "title": "전력사용현황",
    "contentLength": 3283,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/report.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reportFine.js?v=0.0.2"
    ],
    "textPreview": "전력사용현황 전력사용현황 사용월 조회 저장 ※ 설비별 전력사용현황 구분 현황 누적현황 당월 전월 증감 금년 전년 증감",
    "fetchedAt": "2026-08-28 04:50:48"
  },
  {
    "id": 34,
    "categoryId": 10,
    "menuName": "가상부하분산",
    "pageFile": "loads.html",
    "url": "https://watt.rfenms.com/loads.html",
    "menuDisabled": false,
    "expectedTitle": "가상 부하분산",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/loads.html",
    "title": "가상 부하분산",
    "contentLength": 5716,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/loads.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/amcharts/core.js",
      "./assets/js/lib/amcharts/charts.js",
      "./assets/js/lib/amcharts/themes/dark.js",
      "./assets/js/lib/amcharts/themes/animated.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/loads.js?v=0.0.2"
    ],
    "textPreview": "가상 부하분산 가상 부하분산 날짜 조회 전체 경부하 123,456,000원 중부하 123,456,000원 최대부하 123,456,000원 가나다라마바사 경부하 123,456,000원 중부하 123,456,000원 최대부하 123,456,000원 최대부하 50%",
    "fetchedAt": "2026-08-28 04:50:48"
  },
  {
    "id": 35,
    "categoryId": 11,
    "menuName": "종합보고서",
    "pageFile": "report.html",
    "url": "https://watt.rfenms.com/report.html",
    "menuDisabled": false,
    "expectedTitle": "보고서 - 종합보고서",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/report.html",
    "title": "보고서 - 종합보고서",
    "contentLength": 5265,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/report.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/report.js?v=0.0.2"
    ],
    "textPreview": "보고서 - 종합보고서 종합 보고서 설비 설비 목록 준비 기간 ~ 조회 엑셀로 다운 날짜 최대수요 ( kW ) 전력량 ( kWh ) 전력요금/생산량 전력요금 ( 원 ) TOE TCO₂ 역률 ( % ) 부하율 ( % ) - - - - - - - - -",
    "fetchedAt": "2026-08-28 04:50:48"
  },
  {
    "id": 36,
    "categoryId": 11,
    "menuName": "전력요금보고서",
    "pageFile": "reportPower.html",
    "url": "https://watt.rfenms.com/reportPower.html",
    "menuDisabled": false,
    "expectedTitle": "보고서 - 전력요금보고서",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/reportPower.html",
    "title": "보고서 - 전력요금보고서",
    "contentLength": 10150,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/report.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reportPower.js?v=0.0.2"
    ],
    "textPreview": "보고서 - 전력요금보고서 전력요금 보고서 요금제: 준비 설비 설비 목록 준비 날짜 조회 저장 요금표 구분 월 전력사용량 ( kWh ) 월 전력사용요금 ( 원 ) 중간부하 - - 최대부하 - - 경부하 - - 전체 - - 구분 연 전력사용량 ( kWh ) 연 전력사용요금 ( 원 ) 중간부하 - - 최대부하 - - 경부하 - - 전체 - - 일자 시간별 전력량 요금 ( 만원 ) 전력량요금 ( 만원 ) 역률 ( % ) 1 2 3 4",
    "fetchedAt": "2026-08-28 04:50:49"
  },
  {
    "id": 37,
    "categoryId": 11,
    "menuName": "전력사용량분석보고서",
    "pageFile": "reportIK.html",
    "url": "https://watt.rfenms.com/reportIK.html",
    "menuDisabled": true,
    "expectedTitle": "전력사용량분석보고서 - 일광금속",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/reportIK.html",
    "title": "전력사용량분석보고서 - 일광금속",
    "contentLength": 106011,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/metered.css?v=0.0.1"
    ],
    "scripts": [
      "https://cdn.jsdelivr.net/npm/echarts@5.4.0/dist/echarts.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reportIK.js?v=0.0.2"
    ],
    "textPreview": "전력사용량분석보고서 - 일광금속 전력 사용량 분석 보고서 날짜 조회 1. 전력 사용 현황 및 대비 1-1)전월대비 전력사용 증감량 ※전월 대비 증가 감소 구분 단위 기간 일광금속 합계 유한회사 제2공장 일광정공 소계 단조A (950kW) 단조C (890kW) 가공D (950kW) 가공E (950kW) 천안 (950kW) 천안2 (950kW) 소계 제2공장A (900kW) 사봉 (950kW) 일광정공 (500kW) 사용량 1,0",
    "fetchedAt": "2026-08-28 04:50:49"
  },
  {
    "id": 38,
    "categoryId": 11,
    "menuName": "온실가스배출보고서",
    "pageFile": "reportToe.html",
    "url": "https://watt.rfenms.com/reportToe.html",
    "menuDisabled": false,
    "expectedTitle": "보고서 - 온실가스배출보고서",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/reportToe.html",
    "title": "보고서 - 온실가스배출보고서",
    "contentLength": 10127,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/report.css?v=0.0.1",
      "./assets/css/reportToe.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reportToe.js?v=0.0.2"
    ],
    "textPreview": "보고서 - 온실가스배출보고서 온실가스 배출 보고서 요금제: 준비 설비 설비 목록 준비 날짜 조회 저장 구분 월 전력사용량 ( kWh ) 월 온실가스 배출량 ( kgCO 2 ) 중간부하 - - 최대부하 - - 경부하 - - 전체 - - 구분 연 전력사용량 ( kWh ) 연 온실가스 배출량 ( kgCO 2 ) 중간부하 - - 최대부하 - - 경부하 - - 전체 - - 일자 최대배출량 최대배출 시간별 온실가스 배출량 ( kgCO 2",
    "fetchedAt": "2026-08-28 04:50:49"
  },
  {
    "id": 39,
    "categoryId": 11,
    "menuName": "기간별 전력사용량",
    "pageFile": "reportUnit.html",
    "url": "https://watt.rfenms.com/reportUnit.html",
    "menuDisabled": false,
    "expectedTitle": "보고서 - 기간별 전력사용량",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/reportUnit.html",
    "title": "보고서 - 기간별 전력사용량",
    "contentLength": 4388,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/report.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reportUnit.js?v=0.0.2"
    ],
    "textPreview": "보고서 - 기간별 전력사용량 기간별 전력사용량 기간 시간단위 일단위 월단위 날짜 ~ 검색 조회 엑셀로 다운 -",
    "fetchedAt": "2026-08-28 04:50:49"
  },
  {
    "id": 40,
    "categoryId": 11,
    "menuName": "설비별 전력상세정보",
    "pageFile": "reportFacilities.html",
    "url": "https://watt.rfenms.com/reportFacilities.html",
    "menuDisabled": false,
    "expectedTitle": "보고서 - 설비별 전력상세정보",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/reportFacilities.html",
    "title": "보고서 - 설비별 전력상세정보",
    "contentLength": 6908,
    "styles": [
      "./assets/css/lib/tui-time-picker.css",
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/report.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/lib/tui-time-picker.js",
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reportFacilities.js?v=0.0.2"
    ],
    "textPreview": "보고서 - 설비별 전력상세정보 설비별 전력상세정보 데이터방향 가로 세로 기간 ~ 시간단위 일일단위 월간단위 조회 저장 전압(V) 전류(A) 전력(kW) 전력량(kWh) 무효전력량(kVarh) 역률(%) 전력요금(원) 누적요금(원) 순간최대전력(kW) 구분 설비명 항목 전압(V) 전류(A) 전력(kW) 전력량(kWh) 무효전력량(kVarh) 역률(%) 전력요금(원)",
    "fetchedAt": "2026-08-28 04:50:49"
  },
  {
    "id": 41,
    "categoryId": 11,
    "menuName": "공정별 보고서",
    "pageFile": "reportTotal.html",
    "url": "https://watt.rfenms.com/reportTotal.html",
    "menuDisabled": false,
    "expectedTitle": "보고서 - 공정별 보고서",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/reportTotal.html",
    "title": "보고서 - 공정별 보고서",
    "contentLength": 13913,
    "styles": [
      "./assets/css/lib/tui-date-picker.css",
      "./assets/css/lib/select2.min.css",
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/reportTotal.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/lib/tui-date-picker.js",
      "./assets/js/lib/xlsx.full.min.js",
      "./assets/js/jquery.min.js",
      "./assets/js/lib/jquery-ui.js",
      "./assets/js/lib/select2.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/reportTotal.js?v=0.0.2"
    ],
    "textPreview": "보고서 - 공정별 보고서 공정별 보고서 요금제 : 산업용(을)고압A 선택II 일별 월별 연별 기간 ~ 분류 공정전체 공정 소분류 중분류 대분류 조회 상세조건 엑셀로 다운 에너지사용 전력사용량 전력사용비율 경부하 중부하 최대부하 경부하율 중부하율 최대부하율 역률 도시가스사용량 용수사용량 사용요금 전력요금 경부하요금 중부하요금 최대부하요금 도시가스 사용요금 용수 사용요금 생산량 및 환경 생산량 원단위 TOE tCO 2 tCO 2 ",
    "fetchedAt": "2026-08-28 04:50:49"
  },
  {
    "id": 42,
    "categoryId": 12,
    "menuName": "로그인",
    "pageFile": "login.html",
    "url": "https://watt.rfenms.com/login.html",
    "menuDisabled": false,
    "expectedTitle": "한국미래에너지",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/login.html",
    "title": "한국미래에너지",
    "contentLength": 2114,
    "styles": [
      "./assets/css/common.css?v=0.0.1",
      "./assets/css/login.css?v=0.0.1"
    ],
    "scripts": [
      "./assets/js/jquery.min.js",
      "./assets/js/base.js?v=0.0.1",
      "./assets/js/login.js?v=0.0.2"
    ],
    "textPreview": "한국미래에너지 ABC 에너지 통합관제 시스템 Login 아이디저장 LOGIN",
    "fetchedAt": "2026-08-28 04:50:50"
  },
  {
    "id": 43,
    "categoryId": 13,
    "menuName": "좌측 메뉴",
    "pageFile": "include/leftnav.html",
    "url": "https://watt.rfenms.com/include/leftnav.html",
    "menuDisabled": false,
    "expectedTitle": "",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/include/leftnav.html",
    "title": "",
    "contentLength": 7907,
    "styles": [],
    "scripts": [],
    "textPreview": "통합관제 업체관리 대시보드 대시보드 위젯 대시보드 전력메인 태양광 대시보드 컨설팅 피크관리 피크상태 부하상황판 피크 제어설정 피크 그래프 전력 사용 보고서 피크 15분 전력보고서 피크제어이력 시스템에어컨 전력사용량 전력사용량 보기 소비량 예측 절감효과 계통감시 계통감시 공정별 에너지 계통 설비관리 제어설비목록 주요설비 이용률 주요설비 부하율 설비 제어 최적화 제어 최적화 제어이력 콤프레셔 온도 가스 사용량 냉난방 제어 PLC ",
    "fetchedAt": "2026-08-28 04:50:50"
  },
  {
    "id": 44,
    "categoryId": 13,
    "menuName": "상단바",
    "pageFile": "include/top.html",
    "url": "https://watt.rfenms.com/include/top.html",
    "menuDisabled": false,
    "expectedTitle": "",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/include/top.html",
    "title": "",
    "contentLength": 3397,
    "styles": [],
    "scripts": [],
    "textPreview": "주의요함 이번주는 피크관리에 각별한 관심이 필요합니다! 관심필요 이번주 피크 횟수가 평균을 초과하였습니다. 보통 이번주 피크현황이 안정적입니다. 좋아요! 이번주 에너지 사용이 원활합니다. 환경설정 대시보드 화면설정 사용자관리 알람설정 게이트웨이 관리 복합제어기 관리 시퀀스제어 RTU관리 모드버스 계측 실시간데이터 통신상태 불량 업데이트 새로고침 도움말 로그아웃",
    "fetchedAt": "2026-08-28 04:50:50"
  },
  {
    "id": 45,
    "categoryId": 13,
    "menuName": "대시보드 위젯",
    "pageFile": "include/widget.html",
    "url": "https://watt.rfenms.com/include/widget.html",
    "menuDisabled": false,
    "expectedTitle": "",
    "httpStatus": 200,
    "finalUrl": "https://watt.rfenms.com/include/widget.html",
    "title": "",
    "contentLength": 69552,
    "styles": [],
    "scripts": [],
    "textPreview": "실시간 피크 전력 00:00 / 15:00 0 kw 0 % 0 kw 안정 근접 초과 오늘의 피크 시간대 00:00 지난주 동시간 대비 0 kW 0 ( 0 kWh) 실시간 전력 사용량 00:00 / 60:00 경부하 중부하 최대부하 최근 1시간당 사용량 ~00:00 전주 동일 시간 대비 0 kWh 0 ( 0 kWh) 오늘 누적 사용량 ~00:00 전주 동일 시간 대비 0 kWh 0 ( 0 kWh) 오늘의 전력 사용량 오늘 0 k",
    "fetchedAt": "2026-08-28 04:50:50"
  }
];

/** 카테고리(ord 순)별 페이지 묶음 */
export function getMockPagesByCategory(): { category: MockCategory; pages: MockPage[] }[] {
  return MOCK_CATEGORIES.map((category) => ({
    category,
    pages: MOCK_PAGES.filter((p) => p.categoryId === category.id),
  }));
}
