/**
 * data/pages.db(파이어크롤 수집 결과)를 읽어 앱에서 바로 import 가능한
 * MockDB 모듈(src/lib/mock-db.ts)을 생성한다.
 * - html 원문은 용량이 커서 제외하고, 화면 구성에 필요한 메타/요약만 담는다.
 *
 * 실행: node scripts/build-mock-db.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const DB_PATH = path.join(ROOT, 'data', 'pages.db');
const SUMMARY_PATH = path.join(ROOT, 'data', 'fetch-summary.json');
const OUT_PATH = path.join(ROOT, 'src', 'lib', 'mock-db.ts');
const TEXT_PREVIEW_LEN = 240;

const db = new DatabaseSync(DB_PATH, { readOnly: true });

const categories = db
  .prepare('SELECT id, ord, name, disabled FROM categories ORDER BY ord')
  .all()
  .map((c) => ({ id: c.id, ord: c.ord, name: c.name, disabled: !!c.disabled }));

const pages = db
  .prepare(
    `SELECT p.id, p.category_id, p.menu_name, p.page_file, p.url, p.menu_disabled,
            p.expected_title, p.http_status, p.final_url, p.title, p.content_length,
            p.styles, p.scripts, p.text_content, p.fetched_at
     FROM pages p JOIN categories c ON c.id = p.category_id
     ORDER BY c.ord, p.id`,
  )
  .all()
  .map((p) => ({
    id: p.id,
    categoryId: p.category_id,
    menuName: p.menu_name,
    pageFile: p.page_file,
    url: p.url,
    menuDisabled: !!p.menu_disabled,
    expectedTitle: p.expected_title ?? '',
    httpStatus: p.http_status ?? 0,
    finalUrl: p.final_url ?? '',
    title: p.title ?? '',
    contentLength: p.content_length ?? 0,
    styles: JSON.parse(p.styles || '[]'),
    scripts: JSON.parse(p.scripts || '[]'),
    textPreview: (p.text_content || '').slice(0, TEXT_PREVIEW_LEN),
    fetchedAt: p.fetched_at,
  }));

db.close();

const summary = JSON.parse(readFileSync(SUMMARY_PATH, 'utf8'));

const header = `/**
 * AUTO-GENERATED by scripts/build-mock-db.mjs — 직접 수정하지 말 것.
 * 원본: data/pages.db (파이어크롤 수집, ${summary.fetchedAt})
 * 재생성: node scripts/build-mock-db.mjs
 */`;

const body = `${header}

export interface MockCategory {
  id: number;
  ord: number;
  name: string;
  disabled: boolean;
}

export interface MockPage {
  id: number;
  categoryId: number;
  menuName: string;
  pageFile: string;
  url: string;
  menuDisabled: boolean;
  expectedTitle: string;
  httpStatus: number;
  finalUrl: string;
  title: string;
  contentLength: number;
  styles: string[];
  scripts: string[];
  textPreview: string;
  fetchedAt: string;
}

export interface MockFetchSummary {
  categories: number;
  pagesTotal: number;
  pagesOk: number;
  failures: string[];
  fetchedAt: string;
}

export const MOCK_FETCH_SUMMARY: MockFetchSummary = ${JSON.stringify(
  {
    categories: summary.categories,
    pagesTotal: summary.pagesTotal,
    pagesOk: summary.pagesOk,
    failures: summary.failures,
    fetchedAt: summary.fetchedAt,
  },
  null,
  2,
)};

export const MOCK_CATEGORIES: MockCategory[] = ${JSON.stringify(categories, null, 2)};

export const MOCK_PAGES: MockPage[] = ${JSON.stringify(pages, null, 2)};

/** 카테고리(ord 순)별 페이지 묶음 */
export function getMockPagesByCategory(): { category: MockCategory; pages: MockPage[] }[] {
  return MOCK_CATEGORIES.map((category) => ({
    category,
    pages: MOCK_PAGES.filter((p) => p.categoryId === category.id),
  }));
}
`;

writeFileSync(OUT_PATH, body);
console.log(`생성 완료: ${OUT_PATH}`);
console.log(`카테고리 ${categories.length}개 / 페이지 ${pages.length}개 (수집일 ${summary.fetchedAt})`);
